[DNN.size]
nGRU = 2
gru_scale_s = 2
gru_scale_k = 4

[Train]
train_iter = 2000
valid_period = 25
batch_size = 1

[Lorenz]
q2_db = -30
v_db = 0
is_linear = 1
# alpha = 0 -- Lorenz attractor, alpha = 1 -- Chen attractor
alpha = 0
beta = 0.0

delta = 0.02
Taylor = 5
theta = 0
# 1=early_stop 0=not_early_stop
danse_early_stop = 0
danse_es_patience = 3
danse_es_min_delta = 5e-2
; train_seq_len = 15
train_seq_len = 100
train_seq_num = 100
valid_seq_len = 500
valid_seq_num = 5
test_seq_len = 500
test_seq_num = 10

[Train.DANSE]
learning_rate = 1e-3

[Train.Kalman]
learning_rate = 5e-4
weight_decay = 0

[Train.Split]
learning_rate = 1e-2
weight_decay = 0
alter_period = 1
